# @package _global_

dataset:
  view_sampler:
    min_distance_between_context_views: 30
    max_distance_between_context_views: 60
    min_distance_to_context_views: 0
    warm_up_steps: 5000
    initial_min_distance_between_context_views: 20
    initial_max_distance_between_context_views: 40
    num_target_views: 4