defaults:
  - dataset: arkit_scenes
  - optional dataset/view_sampler_dataset_specific_config: ${dataset/view_sampler}_${dataset}
  - model/encoder: depthsplat
  - model/decoder: splatting_cuda
  - loss: [mse]

wandb:
  project: depthsplat
  entity: yuehuarulian
  name: placeholder
  mode: online
  id: null

mode: train

dataset:
  overfit_to_scene: null

data_loader:
  train:
    num_workers: 4
    persistent_workers: true
    batch_size: 4
    seed: 1234
  test:
    num_workers: 4
    persistent_workers: false
    batch_size: 1
    seed: 2345
  val:
    num_workers: 1
    persistent_workers: true
    batch_size: 1
    seed: 3456

optimizer:
  lr: 2.e-4
  lr_monodepth: 2.e-6
  warm_up_steps: 2000
  weight_decay: 0.01

checkpointing:
  load: null
  every_n_train_steps: 5000
  save_top_k: 5
  pretrained_model: null
  pretrained_monodepth: null
  pretrained_mvdepth: null
  pretrained_depth: null
  no_strict_load: false
  resume: false

train:
  depth_mode: null
  extended_visualization: false
  print_log_every_n_steps: 100
  eval_model_every_n_val: 2  # quantitative evaluation every n val
  eval_data_length: 999999
  eval_deterministic: false
  eval_time_skip_steps: 3
  eval_save_model: true
  l1_loss: false
  intermediate_loss_weight: 0.9
  no_viz_video: true
  viz_depth: false
  forward_depth_only: false
  train_ignore_large_loss: 0.
  no_log_projections: false

test:
  output_path: outputs/test
  compute_scores: true
  eval_time_skip_steps: 0
  save_image: true
  save_video: true
  save_gt_image: true
  save_input_images: true
  save_depth: true
  save_depth_npy: false
  save_depth_concat_img: true
  save_gaussian: true
  render_chunk_size: null
  stablize_camera: false
  stab_camera_kernel: 50

seed: 111123

trainer:
  max_steps: -1
  val_check_interval: 0.5
  gradient_clip_val: 0.5
  num_sanity_val_steps: 2

output_dir: outputs/tmp

use_plugins: false
